[package]
name = "v2m_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "v2m_engine"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
cpal = "0.15"
numpy = "0.20"
dasp_ring_buffer = "0.11"
anyhow = "1.0"
log = "0.4"
