site_name: Voice2Machine Frontend
site_url: https://github.com/v2m-lab/voice2machine
repo_url: https://github.com/v2m-lab/voice2machine
edit_uri: edit/main/apps/frontend/docs/docs/

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo oscuro
  features:
    - navigation.expand
    - content.code.copy

nav:
  - Spanish:
      - Inicio: es/index.md
      - Arquitectura: es/arquitectura.md
      - Componentes: es/componentes.md
      - Gestión de Estado: es/estados.md
      - Hooks y Utilidades: es/hooks_utils.md
      - Desarrollo: es/desarrollo.md
      - Estándares: es/estandares.md
  - English:
      - Home: en/index.md
      - Architecture: en/architecture.md
      - Components: en/components.md
      - State Management: en/state_management.md
      - Hooks and Utilities: en/hooks_utils.md
      - Development: en/development.md
      - Standards: en/standards.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
